#    _      ____    _  __     _      _   _   ___      _
#   / \    |  _ \  | |/ /    / \    | \ | | |_ _|    / \
#  / _ \   | |_) | | ' /    / _ \   |  \| |  | |    / _ \
# / ___ \  |  _ <  | . \   / ___ \  | |\  |  | |   / ___ \
#/_/   \_\ |_| \_\ |_|\_\ /_/   \_\ |_| \_| |___| /_/   \_\
#
#@author: Julien

name: ArkaniaStudios-Core
version: 2.0.0
main: arkania\Core
api: 4.14.1
authors:
  - Julien
description: Tous ce qui est développé par nos équipes, ou qui concerne le serveur, restent confidentiels et est interdit à l’utilisation tiers.
website: https://github.com/ArkaniaStudios
permissions:
    "arkania:permission.npc":
        default: op
    "arkania:permission.addrank":
        default: op
    "arkania:permission.delrank":
        default: op
    "arkania:permission.vanish":
        default: op
    "arkania:permission.kick":
        default: op
    "arkania:permission.logs":
        default: op
    "arkania:permission.redem":
        default: op
    "arkania:permission.settings.bypass":
        default: op
    "arkania:permission.setrank":
        default: op
    "arkania:permission.setformat":
        default: op
    "arkania:permission.setnametag":
        default: op
    "arkania:permission.addpermission":
        default: op
    "arkania:permission.delpermission":
        default: op
    "arkania:permission.addupermission":
        default: op
    "arkania:permission.delupermission":
        default: op
    "arkania:permission.ranks":
        default: op
    "arkania:permission.listpermission":
        default: op
    "arkania:permission.listupermission":
        default: op
    "arkania:permission.faction.addpower":
        default: op
    "arkania:permission.faction.delpower":
        default: op
    "arkania:permission.faction.forcedisband":
        default: op
    "arkania:permission.faction.addmoney":
        default: op
    "arkania:permission.faction.delmoney":
        default: op
    "arkania:permission.maintenance":
        default: op
    "arkania:permission.maintenance.bypass":
        default: op
    "arkania:permission.cooldown.bypass":
        default: op
    "arkania:permission.selector.staff":
        default: op
    "arkania:permission.debug":
        default: op
    "arkania:permission.addmoney":
        default: op
    "arkania:permission.delmoney":
        default: op
    "arkania:permission.setmoney":
        default: op
    "arkania:permission.resetmoney":
        default: op
    "arkania:permission.adminkit":
        default: op
    "arkania:permission.kit.booster":
        default: op
    "arkania:permission.kit.noble":
        default: op
    "arkania:permission.kit.hero":
        default: op
    "arkania:permission.kit.seigneur":
        default: op
    "arkania:permission.kit.videaste":
        default: op
    "arkania:permission.staffmode":
        default: op
    "arkania:permission.tempsban":
        default: op
    "arkania:permission.tempsban.bypass":
        default: op
    "arkania:permission.unban":
        default: op
    "arkania:permission.kick.bypass":
        default: op